# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a971c4f1b9f4507318778bc6c468c6b37c7ce0c345e68fe6ed2dbfec54b131ebacf70f4dd5c8b94af74fd3e8b720ffa3556571448a94d7ba0f206b57cb7817a

test:
  secret_key_base: 5b10ed2f8137e0dde4794ab93b9912c7b086a65fde0f2e5afcef561148557bd79d01e699755bf7984f5114f4a6d8afb9bca4bd8c8628db31d63d26d7a164d486

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
